---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint .
  ansible-lint .
platforms:
  - name: jira.cont
    groups:
      - jira
    image: idealista/jdk:1.8.0_202-stretch-oraclejdk
    exposed_ports:
      - 8080/udp
      - 8080/tcp
    published_ports:
      - 0.0.0.0:8080:8080/udp
      - 0.0.0.0:8080:8080/tcp
    privileged: false
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    capabilities:
      - SYS_ADMIN
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: '/lib/systemd/systemd'
    stop_signal: 'RTMIN+3'
provisioner:
  name: ansible
verifier:
  name: ansible
